# Generated by Django 4.0.4 on 2022-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('content', models.CharField(default=None, max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
