# Generated by Django 4.0.4 on 2022-05-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Posts', '0002_post_department_alter_post_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_posts', to='Departments.department'),
        ),
    ]
