# Generated by Django 4.0.4 on 2022-05-05 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(default=datetime.date(2022, 5, 5)),
        ),
    ]
