# Generated by Django 4.0.4 on 2022-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reg', 'Regular Staff'), ('sup', 'Supervisor'), ('mng', 'Manager'), ('dir', 'Director')], default='Regular Staff', max_length=50, null=True),
        ),
    ]
