# Generated by Django 4.0.4 on 2022-05-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
