# Generated by Django 4.0.4 on 2022-05-07 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_dob_alter_customuser_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(default=datetime.date(2022, 5, 7)),
        ),
    ]
