# Generated by Django 4.0.4 on 2022-05-11 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(default=datetime.date(2022, 5, 11)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Regular Staff', 'Regular Staff'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Director', 'Director')], default='Regular Staff', max_length=50, null=True),
        ),
    ]
