# Generated by Django 4.0.4 on 2022-05-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_rename_task_name_task_task_name'),
        ('InventoryItems', '0001_initial'),
        ('Subsections', '0002_subsection_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='subsection_tasks', to='Tasks.task'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='inventory_items',
            field=models.ManyToManyField(blank=True, related_name='subsection_items', to='InventoryItems.inventoryitem'),
        ),
    ]
