# Generated by Django 4.0.4 on 2022-05-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0003_remove_checklist_amount'),
        ('Shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='checklist_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='section_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='checklist',
            field=models.ManyToManyField(to='Shifts.checklistitem'),
        ),
        migrations.AddField(
            model_name='shift',
            name='checklists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='Checklists.checklist'),
        ),
    ]
