# Generated by Django 4.0.4 on 2022-05-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0003_remove_checklist_amount'),
        ('Shifts', '0002_checklistitem_checklist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='checklists',
        ),
        migrations.AddField(
            model_name='shift',
            name='checklists',
            field=models.ManyToManyField(related_name='shifts', to='Checklists.checklist'),
        ),
    ]
