# Generated by Django 4.0.4 on 2022-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0007_checklistitem_assigned_to_alter_checklistitem_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='count',
            new_name='extra_from_checklist_amount',
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='used_as_template',
            field=models.BooleanField(default=False),
        ),
    ]
