# Generated by Django 4.0.4 on 2022-05-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0009_remove_checklistitem_completed_by_shift_boarding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='checklist',
            new_name='checklist_items',
        ),
    ]
