# Generated by Django 4.0.4 on 2022-05-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_name',
            new_name='task_name',
        ),
    ]
