# Generated by Django 4.0.4 on 2022-05-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_checklist',
            field=models.BooleanField(default=False),
        ),
    ]
