# Generated by Django 4.0.4 on 2022-05-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_remove_task_completed_by_task_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to_checklist',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
