# Generated by Django 4.0.4 on 2022-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_rename_comments_task_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
