# Generated by Django 4.0.4 on 2022-05-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_alter_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='section_name',
            field=models.CharField(choices=[('Pre-Departure', 'Pre-Departure'), ('Briefing', 'Briefing'), ('Sightseeing Boat', 'Sightseeing Boat'), ('Last Cruise of the day', 'Last Cruise of the day'), ('Pier Works', 'Pier Works'), ('Kitchen', 'Kitchen'), ('Other', 'Other')], default='Other', max_length=50, null=True),
        ),
    ]
