# Generated by Django 4.0.4 on 2022-05-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0011_task_edited_by_task_extra_from_checklist_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
