# Generated by Django 4.0.4 on 2022-05-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0004_alter_worker_userid'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='workers',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Workers.worker'),
        ),
    ]
