# Generated by Django 4.0.4 on 2022-05-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0002_alter_checklist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='amount',
        ),
    ]
