# Generated by Django 4.0.4 on 2022-05-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0002_alter_checklist_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='extraFromChecklistAmount',
            new_name='extra_from_checklist_amount',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Task_name',
            new_name='task_name',
        ),
    ]
