# Generated by Django 4.0.4 on 2022-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subsections', '0003_subsection_tasks_alter_subsection_inventory_items'),
        ('Checklists', '0003_rename_extrafromchecklistamount_inventoryitem_extra_from_checklist_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='chcklist_sections',
            field=models.ManyToManyField(blank=True, related_name='checklist_sections', to='Subsections.subsection'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
