# Generated by Django 4.0.4 on 2022-05-05 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0004_checklist_chcklist_sections_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='Subsection',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='chcklist_sections',
            new_name='cheklist_sections',
        ),
    ]
