# Generated by Django 4.0.4 on 2022-05-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checklists', '0006_rename_cheklist_sections_checklist_checklist_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_sections',
        ),
    ]
