# Generated by Django 4.0.4 on 2022-05-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryItems', '0002_inventoryitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_to_checklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
