# Generated by Django 4.0.4 on 2022-05-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryItems', '0004_remove_inventoryitem_completed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='assigned_to_checklist',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='completed_status',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='order',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='comment',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
