# Generated by Django 4.0.4 on 2022-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryItems', '0005_rename_item_name_inventoryitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
