# Generated by Django 4.0.4 on 2022-05-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryItems', '0006_alter_inventoryitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='section_name',
            field=models.CharField(choices=[('Crockery', 'Crockery'), ('Cutlery', 'Cutlery'), ('Serving Tools', 'Serving Tools'), ('Food Serivce Area', 'Food Serivce Area'), ('Drinks Bar', 'Drinks Bar'), ('Supervising', 'Supervising'), ('Other', 'Other')], default='Other', max_length=50, null=True),
        ),
    ]
