# Generated by Django 4.0.4 on 2022-05-01 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='userID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='registeredAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
