# Generated by Django 4.0.4 on 2022-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0004_alter_worker_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
