# Generated by Django 4.0.4 on 2022-05-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0005_alter_worker_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='userID',
        ),
    ]
