# Generated by Django 4.0.4 on 2022-05-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Workers', '0006_remove_worker_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='userID',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
