# Generated by Django 4.0.4 on 2022-05-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0007_worker_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='userID',
        ),
    ]
